aliases:
  restore_cache_step: &restore_cache_step
    restore_cache:
      key: dependency-cache-{{ checksum "yarn.lock" }}
  save_cache_step: &save_cache_step
    save_cache:
      key: dependency-cache-{{ checksum "yarn.lock" }}
      paths:
        - ./node_modules
  install_dependencies_step: &install_dependencies_step
    run:
      name: install-dependencies
      command: yarn install

  unit_test: &unit_test
    steps:
      - checkout
      - *restore_cache_step
      - *install_dependencies_step
      - *save_cache_step
      - run:
          name: tests
          command: 'yarn jest --ci --reporters=default'

version: 2
jobs:
  node-v16-latest:
    docker:
      - image: cimg/node:22.4
    <<: *unit_test
  node-v18-latest:
    docker:
      - image: cimg/node:22.4
    <<: *unit_test
  node-v20-latest:
    docker:
      - image: cimg/node:22.4
    <<: *unit_test
  deploy:
    docker:
      - image: cimg/node:22.4
    steps:
      - checkout
      - *restore_cache_step
      - *install_dependencies_step
      - *save_cache_step
      - run:
          name: Publish package
          command: npx semantic-release

workflows:
  version: 2
  test-deploy:
    jobs:
      - node-v16-latest
      - node-v18-latest
      - node-v20-latest
      - deploy:
          requires:
            - node-v16-latest
            - node-v18-latest
            - node-v20-latest
          filters:
            branches:
              only: master
